### ISSUE TITLE
Textbook Exchange TODO

### ISSUE THREAD

**Issue by emumoo** [thecourseforum/theCourseForum#145]
- [ ] Create "My Listings" page - with renew/cancel & report
- [ ] Apply validations for posting (cellphone)
- [ ] Provide choice of SMS/email in post & claim modals
- [ ] Display all listing information in claim modal

Feel free to add any additional tasks
